### ISSUE TITLE
BUG : Google Analytics 4 Destination loads latest version of `browser.js` not installed version

### ISSUE THREAD

**Issue by jbean96** [rudderlabs/rudder-sdk-js#1118]
**Describe the bug**

It appears that when using the Google Analytics 4 destination, the `browser.js` script that is loaded during initialization is not the one bundled with `rudder-sdk-js`. In our case this results in an error from Rudderstack: `[handleError]:: "[Analytics] 'integration.init()' failed :: GA4_RS :: Cannot read properties of undefined (reading 'sessionInfo')"`

Digging in it appears that this is the segment of code causing this issue:

```
if (this.isHybridModeEnabled && this.overrideClientAndSessionId) {
  gtagParameterObject.client_id = this.analytics.anonymousId;
  // This line, uSession appears to be undefined.
  gtagParameterObject.session_id = this.analytics.uSession.sessionInfo.id;
}
```

Which can be found in the `browser.js` file for the `GA4` integration for the most recent release, however, the `browser.js` file for the currently installed release in our app is `2.14.0` does not reference `this.analytics.uSession` at all.

This leads me to believe that when the integration is initialized `rudder-sdk-js` isn't using the bundled version of GA4's integration and instead is fetching it from the CDN and receiving the most recent version.

**To Reproduce**

1. Open the developer tools panel to the "Console" tab
2. Go to `arrived.com`
3. See the error pop-up

It's possible by the time this issue is reviewed we will have updated to the latest version of `rudder-sdk-js` which I expect will resolve the issue.

**Expected behavior**

GA4 should load successfully.

**Screenshots**

![image](https://github.com/rudderlabs/rudder-sdk-js/assets/22803097/27b190f5-bd00-47e9-883f-3e7cdf22d7f8)

**Additional Information (please complete the following information):**

- SDK installation: NPM
- NPM Version: `9.4.0`
- `rudder-sdk-js` version: `2.14.0`
- Webpage URL: arrived.com
- Integration that has the issue: GA4
- Used JS Framework: React

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Chrome
- Version: `113.0.5672.126`

**Comment by MoumitaM** [comment]
Hello @jbean96, Thank you for raising this. This is what happens when you use an older version (<2.22.0) of `rudder-sdk-js`, for you it's 2.14.0, core SDK version 2.14.0 but the SDK pulls the latest destination SDKs which might not be compatible with the older version of SDK.
To rectify this situation we have introduced a new load option(**`lockIntegrationsVersion`**) to lock the destination version the same as the core SDK version in the **2.22.0** release. [Ref](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/#loading-options)

The version you are using is 8 months old. I will suggest you test and use our latest version with `lockIntegrationsVersion` set to true. Hoping that will solve your problem.

**Comment by MoumitaM** [comment]
There are some limitations which are why we couldn't make it true by default.

**Comment by MoumitaM** [comment]
@jbean96, Have you tried it out? Can we close this issue?

**Comment by jbean96** [comment]
> @jbean96, Have you tried it out? Can we close this issue?

Yup! Updating solved the issue. Thanks for following up.
