### ISSUE TITLE
Add ability to disable integrations/plugins CDN

### ISSUE THREAD

**Issue by adrianlyjak** [rudderlabs/rudder-sdk-js#1938]
I'm confused why the new v3 javascript sdk is reaching out to a CDN to load various plugins and integrations. I would like the full script to be embedded in the NPM package that I already loaded.

I understand that I could self host these, but that seems rather extreme. Would prefer to just have the loaded in my existing bundler.

I tried upgrading to v3, and am now running into rudderstack no longer working in Firefox with enhanced-track-protection, since, unsurprisingly, it marks these rudderlabs CDN urls as tracking urls.

![image](https://github.com/user-attachments/assets/8c025bdb-f719-44b0-8e7b-f9c19dbf48ab)

**Comment by saikumarrs** [comment]
Hi @adrianlyjak 
Thanks for reaching out.

In the v3 version, we've refactored the non-essential functionalities of the SDK into plugins that can be hot-loaded based on the config and browser capabilities.
The integrations will not be part of the SDK bundle as far too many of them exist.

If you use the NPM package, you can use a different export that bundles core and all the plugins together, `@rudderstack/analytics-js/bundled`. Just so you know, the final bundle size will increase due to the presence of plugins.

You can set up custom proxies if you have connected any device mode destinations to your source.

Please let us know if you need any help.

**Comment by saikumarrs** [comment]
Hi @adrianlyjak 
For your use case, you can disconnect the device mode destinations from your JavaScript source. If you want to temporarily avoid loading destinations on the client side, you can configure it in the load API options.

```
rudderanalytics.load(writeKey, dpUrl, {
  integrations: {
    All: false
  }
});
```

Please refer to https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/filtering/#filter-destinations-while-loading-sdk for more details.

**Comment by saikumarrs** [comment]
Hi @adrianlyjak 
Plugins and integrations are separate components. With the above load option, you can only let the SDK know to avoid loading any integrations.

If you don't want to load any plugins, set the `plugins` load API option to an empty array. Please note that you'll lose multiple useful features as a result.
I'd recommend you import the bundled export from the package, if your sole intention is to avoid additional resource requests from the SDK.
