### ISSUE TITLE
userId default to empty string instead of nullish

### ISSUE THREAD

**Issue by lxcid** [rudderlabs/rudder-sdk-js#201]
https://github.com/rudderlabs/rudder-sdk-js/blob/d1c478db7a07feaf3ad87b8c484437f4cfa1254f/analytics.js#L101

`userId` default to empty string instead of nullish, this cause it to forward to destination like google analytics and got identify as a user if they do not check for falsy case in `userId`.

I like to know if this is to be expected? if so can destinations also not send empty string to destination so that they don’t get identify as user when they are actually anonymous?

We are unsure if we force nullish check will it break any existing assumption or should falsy be the check for userId always?

**Comment by ruchiramoitra** [comment]
userId if sent ""  (empty string) will result in no identify call and if a track call is made   a call without any userId will be sent. 
If userId with any value is sent an identify call will be made with  that userId (if send userId is on from our dashboard)  and if a track call is made a call with that userId will be made.
Example: 
      window.rudderanalytics.identify("");
      window.rudderanalytics.track('Simple event 2');
      
<img width="698" alt="Screenshot 2021-02-03 at 8 20 17 PM" src="https://user-images.githubusercontent.com/31311577/106780189-c0f9d900-666d-11eb-908c-0eedf955cb64.png">

      window.rudderanalytics.identify("Steven");
      window.rudderanalytics.track('Simple event');
      
      
<img width="643" alt="Screenshot 2021-02-03 at 8 20 36 PM" src="https://user-images.githubusercontent.com/31311577/106780232-c8b97d80-666d-11eb-9b6a-284c0fb2e570.png">



It would be better if I could get more information about your case and problem so that I can help out.

**Comment by lxcid** [comment]
I only of pieces of our finding and not sure how helpful it will be for you guys but the problem might be with some transformers.

For example, in GA transformer:

https://github.com/rudderlabs/rudder-transformer/blob/ee3273f955b546d8a4d94fa17f66923e3db588e1/v0/destinations/ga/transform.js#L228

During some of our test I think maybe we found out that `userId` is an empty string, but we later found out that for Google Analytics, that is not a spec'ed attributed.

https://github.com/rudderlabs/rudder-transformer/blob/ee3273f955b546d8a4d94fa17f66923e3db588e1/v0/destinations/ga/transform.js#L209-L211

We also find out that `userId` is check falsily.

and if we didn't provide `cid`, it will generate md5 hash of `userId`, which seems to be quite quirky with GA when it come to session unification.

We are still tidying up our thoughts but I think this is not an issue for us anymore due to improved understanding of spec and codebase. Sorry about that, feel free to close this.

**Comment by sayan-mitra** [comment]
thanks for reviewing the code. Please let us know if you face any issues.
Closing this one.
