### ISSUE TITLE
Feature Request: support for HTTP `Set-Cookie` header

### ISSUE THREAD

**Issue by alberto-of** [rudderlabs/rudder-sdk-js#946]
**Is your feature request related to a problem? Please describe.**
ITP of Safari sets the lifetime of the first-party cookie to 7 days. We want to have 1 year.

**Describe the solution you'd like**
The current solution is to use the HTTP header `Set-Cookie` to set the Segment cookie server side and configure `rudder-sdk-js` [to load it](https://github.com/rudderlabs/rudder-sdk-js/blob/1a78d6d02709e3f133a38d4b01f4bb062eefa9ba/src/utils/storage/storage.js#L234).

We would like to have an official support for the HTTP header `Set-Cookie` that works for all RudderStack cookies.

**Describe alternatives you've considered**
We are not aware of alternatives.

**Additional context**
[ITP details](https://www.cookiestatus.com/safari/#other-first-party-storage)

**Comment by MoumitaM** [comment]
Hello @alberto-of ,
Thank you for raising this request. We will look into it and get back to you as soon as possible.

**Comment by bardisg** [comment]
Hello @alberto-of,

In order to ensure we understand the requirement right, can you please verify for us:

1. At the moment you explicitly set a server side cookie, via your server side solutions, with name 'segment' in your top domain (or same domain) and with anonymousId as value, using the segment migration mechanism as a workaround in order to retrieve the anonymousId value from the cookie in subsequent visits that are done after 7 days in Safari.
2. What you would like for us to offer is a way to read the values of our RudderStack specific cookies from server side cookies, that you have created via your server side solutions, in order to stop using a workaround and gain the ability to retain more values, not just anonymousId.

**Comment by alberto-of** [comment]
Hi @bardisg ,

The domain does not contain `segment` but it is the same of our website to keep the first-party context. The rest is correct. The problem is to have profiles that last more than 7 days in Safari including all data of the profile, not only the `anonymous_id`.
